server:
  port: 8084

spring:
  datasource:
    username: root
    password: wangyuqi666
    url: jdbc:mysql://localhost:3306/everything_house?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    host: smtp.qq.com
    username: 3164113754@qq.com
    password: sqibbkyollhgdgaf
    properties:
      mail:
        smtp:
          auth: true  # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          starttls: #SMTP加密方式:连接到一个TLS保护连接
            enable: true
            required: true
mybatis-plus:
  mapper-locations:
    classpath*:mapper/*Mapper.xml
  typeAliasesPackage:
    com.house.**.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: C:/Users/wyq/Desktop/springboot学习/my_own_project/everything_house_ui/src/image/

baseStore:
  baseUrl: "http://localhost:"

export:
  exportUrl: "D:/用户信息.xlsx"
