server:
  port: 8084

spring:
  datasource:
    username: root
    password: wangyuqi666
    url: jdbc:mysql://localhost:3306/everything_house?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis-plus:
  mapper-locations:
    classpath*:mapper/*Mapper.xml
  typeAliasesPackage:
    com.house.**.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: C:/Users/wyq/Desktop/springboot学习/my_own_project/everything_house_ui/src/image/

baseStore:
  baseUrl: "http://localhost:"

export:
  exportUrl: "D:/用户信息.xlsx"
