server:
  port: 8084
spring:
  datasource:
    username: root
    password: wangyuqi666
    url: jdbc:mysql://localhost:3306/everything_house?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis-plus:
  mapper-locations:
    classpath*:mapper/*Mapper.xml
  typeAliasesPackage:
    com.house.**.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

